name: UltiTools-Economy
version: '${project.version}'
main: com.ultikits.plugins.economy.UltiEconomy
base-package: com.ultikits.plugins.economy
api-version: 620
authors: [ wisdomme ]
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
